import { Footer } from "antd/lib/layout/layout";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Yeeun's Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>

      <div className={styles.middle}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Yeeun's project!</a>
        </h1>

        <p className={styles.description}>
          <h2>예니의 페이지에 오신 것을 환영합니다!</h2>
        </p>

        <div className={styles.grid}>
          <Image
            src="/images/IMG_2089.JPG"
            alt="Main Image"
            width={300}
            height={220}
          />
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>
        </div>
        <div className={styles.button}> Contact with me</div>
      </div>
      <div className={styles.footer}>
        Yeeunit's project is started.
        <br /> Do not miss it!
      </div>
      <div className={styles.bottom}></div>
    </div>
  );
}
