// import { Footer } from "antd/lib/layout/layout";
// import Head from "next/head";
// import Image from "next/image";
// import styles from "../styles/Home.module.css";
import MainPage from "./mainpage";

export default function Home() {
  // const [isTrue, setIsTrue] = useState(false);
  // const handleOnClick = () => {
  //   setIsTrue((prev) => !prev);
  // };

  return (
    <>
      <MainPage />
    </>

    // <div className={styles.container}>
    //   <Head>
    //     <title>Yeeun's Project</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main className={styles.main}></main>

    //   <div className={styles.middle}>
    //     <h1 className={styles.title}>Welcome to Yeeun's project!</h1>
    //     <p className={styles.description}>
    //       {/* <h2>예니의 페이지에 오신 것을 환영합니다!</h2> */}
    //     </p>
    //     <div className={styles.grid}>
    //       <Image
    //         src="/images/ye1.png"
    //         alt="Main Image"
    //         width={300}
    //         height={300}
    //       />
    //       <a href="/login" className={styles.card}>
    //         <h2>로그인 하기 &rarr;</h2>
    //         <p>로그인해서 더 많은 서비스를 누려보세요!</p>
    //       </a>
    //     </div>{" "}
    //     <br /> <br />
    //     <div
    //       className={styles.button}
    //       // isTrue={isTrue} onClick={handleOnClick}
    //     >
    //       Contact with me
    //     </div>
    //   </div>
    //   <div>
    //     <div className={styles.footer}>
    //       Yeeunit's project is started.
    //       <br /> Do not miss it!
    //     </div>
    //   </div>

    //   {/* <div className={styles.bottom}></div> */}
    // </div>
  );
}
